# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      # NODE_ENV: production
      # BABEL_ENV: production
      BASE_URL: https://api.greenstone.com.br/
    docker:
      - image: circleci/node:8
    working_directory: ~/circleci-demo-workflows
    steps:
      # Download and cache dependencies
      - checkout
      - restore_cache:
          keys:
          - v4-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v4-dependencies-
      - run: pwd
      - run: ls
      - run: npm install
      - run: npm run build
      - run: rm -rf workspace
      - run: mkdir workspace
      - run: cp -rf build workspace/build
      - run: cp -rf package.json
      - persist_to_workspace:
          root: .
          paths: workspace/build
      - save_cache:
          paths:
            - node_modules
          key: v4-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: npm run test
  deploy:
    docker:
      - image: circleci/node:8.9
    working_directory: ~/circleci-demo-workflows
    steps:
      - attach_workspace:
          at: ~/circleci-demo-workflows
      - run: ls
      - run: pwd
      - run: cd workspace
      - run:
          name: Deploy PR to Surge
          command: npm run surge-deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build