# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      # NODE_ENV: production
      # BABEL_ENV: production
      BASE_URL: https://api.greenstone.com.br/
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-
      - run: npm run build
      - run: cp build workspace/build
      - persist_to_workspace:
         root: workspace
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run: npm run test
  deploy:
    docker:
      - image: circleci/node:8.9
    steps:
      - attach_workspace:
         at: /tmp/workspace
      - run: ls
      - run:
          name: Deploy PR to Surge
          command: npm run surge-deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build